config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  devise_for :users, controllers: { registrations: :registrations, confirmations: 'confirmations' }
  root to: 'pages#home'
  get '/profile', to: 'pages#profile'
  get '/feed', to: 'pages#feed'
  get '/notifications', to: 'pages#notifications'
  resources :users, only: [:show] do
    resources :followers, only: [:create]
  end
  resources :followers, only: [:destroy]
  get '/followers/:user_id', to: 'followers#followers', as: 'followers'
  get '/following/:user_id', to: 'followers#following', as: 'following'
  get '/search', to: 'pages#search', as: 'search'
  resources :wishes, except: [:new, :create]
  resources :categories, only: [:index, :show]
  resources :events, except: [:new, :create] do
    resources :comments, only: [:index, :create]
    resources :likes, only: [:create]
    resources :hostings, only: [:create, :new]
  end
  resources :hostings, only: [:update, :destroy]
  resources :comments, only: [:destroy]
  resources :likes, only: [:destroy]
  resources :activities, only: [:show] do
    resources :events, only: [:new, :create]
    resources :wishes, only: [:new, :create]
  end
  resources :conversations do
    resources :messages
  end

  post '/', to: 'pages#wheel'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :hostings, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :conversations, through: :messages
  has_many :wishes, dependent: :destroy
  has_many :activities, through: :wishes
  has_many :events
  has_many :followers, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :age, presence: true, numericality: { only_integer: true }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable
  mount_uploader :photo, PhotoUploader
  include PgSearch
  pg_search_scope :search_by_firstname_and_lastname,
                  against: [:first_name, :last_name],
                  using: {
                    tsearch: { prefix: true }
                  }

  CO_FOUNDERS = %w[lucien@gmail.com izzy@gmail.com ife@gmail.com gaby@gmail.com].freeze
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @events = @user.events
    redirect_to profile_path if current_user == @user
  end
end

app/views/users/show.html.erb
<div class="wrapper profile-wrapper">
  <%= link_to :back do %>
    <%= image_tag 'left_arrow.png', class: "back-button" %>
  <% end %>
  <div class="container text-center profile-container" id="profile-info">
    <% if @user.photo? %>
      <%= cl_image_tag(@user.photo, width: 150, height: 150, crop: :fill, class:"avatar-xl") %>
    <% else %>
      <%= image_tag('default-avatar.png', width: 150, height: 150, crop: :fill, class:"avatar-xl") %>
    <% end %>
    <div class="interaction">
      <div class="follow-unfollow" id="follow-unfollow">
        <% if Follower.find_by(user_id: @user, follower_id: current_user.id).nil? %>
          <%= link_to 'FOLLOW', user_followers_path(@user), method: :post, remote: true, id:"follow" %>
        <% else %>
          <%= link_to 'UNFOLLOW', follower_path(Follower.find_by(user_id: @user, follower_id: current_user.id)), method: :delete, remote: true, id:"unfollow" %>
        <% end %>
      </div>
      <div class="contact">
        <%= link_to 'CONTACT', conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: :post, id:'contact_user' %>
      </div>
    </div>
    <hr>
    <% if User::CO_FOUNDERS.include?(@user.email) %>
      <h1 class="page-title text-center name-profile" style="margin: 40px auto 10px auto !important;"><%= "#{@user.first_name.capitalize} #{@user.last_name.capitalize}" %><strong class="logo-period-profile">.</strong> </h1>
      <p><em>co-founder</em></p>
    <% else %>
      <h1 class="page-title text-center name-profile"><%= "#{@user.first_name.capitalize} #{@user.last_name.capitalize}" %><strong class="logo-period-profile" style="margin: 40px auto !important;">.</strong> </h1>
    <% end %>
    <hr>
    <div class="followers-followings-hostings">
      <div class="hostings">
        <p>Hostings</p>
        <p><%= @user.events.count %></p>
      </div>
      <%= link_to followers_path(@user.id) do %>
        <div class="followers">
          <p>Followers</p>
          <p id="follower_count"><%= @user.followers.count %></p>
        </div>
      <% end %>
      <%= link_to following_path(@user.id) do %>
        <div class="followings">
          <p>Following</p>
          <p id="following_count"><%= Follower.where(follower_id: @user.id).count %></p>
        </div>
      <% end %>
    </div>
  </div>
</div>