config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  devise_for :users, controllers: { registrations: :registrations, confirmations: 'confirmations' }
  root to: 'pages#home'
  get '/profile', to: 'pages#profile'
  get '/feed', to: 'pages#feed'
  get '/notifications', to: 'pages#notifications'
  resources :users, only: [:show] do
    resources :followers, only: [:create]
  end
  resources :followers, only: [:destroy]
  get '/followers/:user_id', to: 'followers#followers', as: 'followers'
  get '/following/:user_id', to: 'followers#following', as: 'following'
  get '/search', to: 'pages#search', as: 'search'
  resources :wishes, except: [:new, :create]
  resources :categories, only: [:index, :show]
  resources :events, except: [:new, :create] do
    resources :comments, only: [:index, :create]
    resources :likes, only: [:create]
    resources :hostings, only: [:create, :new]
  end
  resources :hostings, only: [:update, :destroy]
  resources :comments, only: [:destroy]
  resources :likes, only: [:destroy]
  resources :activities, only: [:show] do
    resources :events, only: [:new, :create]
    resources :wishes, only: [:new, :create]
  end
  resources :conversations do
    resources :messages
  end

  post '/', to: 'pages#wheel'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <div class="navbar-l">
    <div class='weather-icon'>
      <% if @today.downcase.include? "broken clouds" %>
        <p><i class="fas fa-cloud"></i> <%= @temperature %>˚C</p>
      <% elsif @today.downcase.include? "rain" %>
        <p><i class="fas fa-umbrella"></i> <%= @temperature %>˚C</p>
      <% elsif @today.downcase.include? "scattered clouds" %>
        <p><i class="fas fa-cloud"></i> <%= @temperature %>˚C</p>
      <% elsif @today.downcase.include? "few clouds" %>
        <p><i class="fas fa-cloud-sun"></i> <%= @temperature %>˚C</p>
      <% elsif @today.downcase.include? "thunderstorm" %>
        <p><i class="fas fa-bolt"></i> <%= @temperature %>˚C</p>
      <% elsif @today.downcase.include? "clear sky" %>
        <p><i class="fas fa-sun"></i> <%= @temperature %>˚C</p>
      <% elsif @today.downcase.include? "hot" %>
        <p><i class="fas fa-temperature-high"></i> <%= @temperature %>˚C</p>
      <% elsif @today.downcase.include? "foggy" %>
        <p><i class="fas fa-smog"></i> <%= @temperature %>˚C</p>
      <% elsif @today.downcase.include? "snow" %>
        <p><i class="fas fa-snowflake"></i> <%= @temperature %>˚C</p>
      <% elsif @today.downcase.include? "shower rain" %>
        <p><i class="fas fa-cloud-rain"></i> <%= @temperature %>˚C</p>
      <% elsif @today.downcase.include? "windy" %>
        <p><i class="fas fa-wind"></i> <%= @temperature %>˚C</p>
      <% else %>
        <p><i class="fas fa-wind"></i> <%= @temperature %>˚C</p>
      <% end %>
    </div>
  </div>
      <!-- Logo -->
  <div class="navbar-m">
    <div class="logo">
      <%= link_to root_path do %>
        <p class="logo-text">idk<strong class="logo-period">.</strong></p>
      <% end %>
    </div>
  </div>
  <!-- Right Navigation -->

  <div class="navbar-r">
    <div class="navbar-wagon-right hidden-xs hidden-sm">

      <% if user_signed_in? %>

        <!-- Links when logged in -->
        <% conversations = Conversation.where(recipient_id: current_user.id).or(Conversation.where(sender_id: current_user.id)) %>
        <% unread_messages = [] %>
        <% conversations.each do |conversation| %>
          <% conversation.messages.each do |message| %>
            <% unread_messages << message %>
          <% end %>
        <% end %>
        <% unread_messages = unread_messages.reject { |message| message.read || message.user_id == current_user.id }.count %>
        <% if unread_messages.zero? %>
          <%= link_to "INBOX", conversations_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <% else %>
          <%= link_to "INBOX (#{unread_messages})", conversations_path, class: "navbar-wagon-item navbar-wagon-link unread" %>
        <% end %>
        <%= link_to "WISHLIST", wishes_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "FEED", feed_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "MY EVENTS", events_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <% if (Hosting.where(user_id: current_user, status: 'pending') + Follower.where(user_id: current_user, count: 0).or(Follower.where(user_id: current_user, count: 1))).count.zero? %>
          <%= link_to notifications_path, class: "navbar-wagon-item navbar-wagon-link notification-logo" do %>
            <i class="fas fa-bell"></i>
          <% end %>
        <% else %>
          <%= link_to notifications_path, class: "navbar-wagon-item navbar-wagon-link notification-logo" do %>
            <i class="fas fa-bell" style="position: relative;">
              <span class="red-dot" style=" position: absolute; height: 7px; width: 7px; background: red; top: -2px; right: -1px; border-radius: 50%;"></span>
            </i>
          <% end %>
        <% end %>
        <div class="dropdown">
          <i class="fas fa-bars dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to search_path, class: "navbar-wagon-item navbar-wagon-link" do %>
                <i class="fas fa-search"></i> FIND FRIENDS
              <% end %>
            </li>
            <li>
              <% if current_user.photo? %>
                <%= link_to profile_path do %>
                  <%= cl_image_tag current_user.photo, class:'avatar-sm' %> <%= t(".profile", default: "PROFILE") %>
                <% end %>
              <% else %>
                <%= link_to profile_path do %>
                  <%= image_tag 'default-avatar.png', class:'avatar-sm' %> <%= t(".profile", default: "PROFILE") %>
                <% end %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "SIGN OUT") %>
              <% end %>
            </li>
          </ul>
        </div>
      <% else %>
        <div class="login-link-navbar" style="flex-grow: 1">
          <% unless (params[:controller] == "devise/sessions" && (params[:action] == "new" || (params[:action] == "create"))) %>
            <%= link_to t(".sign_in", default: "SIGN IN"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
          <% end %>
          <% if ((params[:controller] == 'devise/sessions') && (params[:action] == 'new' || params[:action] == 'create')) %>
            <%= link_to t(".sign_up", default: "SIGN UP"), new_registration_path(resource_name), class: "navbar-wagon-item navbar-wagon-link" %>
          <% end %>
        </div>
      <% end %>
    </div>

    <!-- Dropdown list appearing on mobile only -->
    <div class="navbar-wagon-item mobile-right hidden-md hidden-lg">
      <% if user_signed_in? %>
        <% if Hosting.where(user_id: current_user.id, status: 'pending').count.zero? %>
          <%= link_to notifications_path, class: "navbar-wagon-item navbar-wagon-link notification-logo" do %>
            <i class="fas fa-bell"></i>
          <% end %>
        <% else %>
          <%= link_to notifications_path, class: "navbar-wagon-item navbar-wagon-link notification-logo" do %>
            <i class="fas fa-bell" style="position: relative;">
              <span class="red-dot" style=" position: absolute; height: 7px; width: 7px; background: red; top: -2px; right: -1px; border-radius: 50%;"></span>
            </i>
          <% end %>
        <% end %>
        <div class="dropdown">
          <% conversations = Conversation.where(recipient_id: current_user.id).or(Conversation.where(sender_id: current_user.id)) %>
          <% unread_messages = [] %>
          <% conversations.each do |conversation| %>
            <% conversation.messages.each do |message| %>
              <% unread_messages << message %>
            <% end %>
          <% end %>
          <% unread_messages = unread_messages.reject { |message| message.read || message.user_id == current_user.id }.count %>
          <% if unread_messages.zero? %>
            <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
          <% else %>
            <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"><span class="red-dot-navbar"><%= unread_messages %></i></span>
          <% end %>
          <ul class="dropdown-menu pull-right navbar-wagon-dropdown-menu">
            <% if unread_messages.zero? %>
              <li>
                <%= link_to conversations_path, class: "navbar-wagon-item navbar-wagon-link" do %>
                  <i class="fas fa-inbox"></i> INBOX
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to conversations_path, class: "navbar-wagon-item navbar-wagon-link unread" do %>
                  <i class="fas fa-inbox"></i> INBOX (<%= unread_messages %>)
                <% end %>
              </li>
            <% end %>
            <li>
              <%= link_to wishes_path, class: "navbar-wagon-item navbar-wagon-link" do %>
                <i class="fas fa-heart"></i> WISHLIST
              <% end %>
            </li>
            <li>
              <%= link_to feed_path, class: "navbar-wagon-item navbar-wagon-link" do %>
                <i class="fas fa-chart-line"></i> FEED
              <% end %>
            </li>
            <li>
              <%= link_to events_path, class: "navbar-wagon-item navbar-wagon-link" do %>
                <i class="far fa-calendar-alt"></i> MY EVENTS
              <% end %>
            </li>
            <li>
              <%= link_to search_path, class: "navbar-wagon-item navbar-wagon-link" do %>
                <i class="fas fa-search"></i> FIND FRIENDS
              <% end %>
            </li>
            <li>
              <% if current_user.photo? %>
                <%= link_to profile_path do %>
                  <%= cl_image_tag current_user.photo, class:'avatar-sm' %> <%= t(".profile", default: "PROFILE") %>
                <% end %>
              <% else %>
                <%= link_to profile_path do %>
                  <%= image_tag 'default-avatar.png', class:'avatar-sm' %> <%= t(".profile", default: "PROFILE") %>
                <% end %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i> <%= t(".sign_out", default: "SIGN OUT") %>
              <% end %>
            </li>
          </ul>
        </div>
      <% else %>
        <% unless (params[:controller] == "devise/sessions" && (params[:action] == "new" || (params[:action] == "create"))) %>
          <%= link_to t(".sign_in", default: "SIGN IN"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <% end %>
        <% if ((params[:controller] == 'devise/sessions') && (params[:action] == 'new' || params[:action] == 'create')) %>
          <%= link_to t(".sign_up", default: "SIGN UP"), new_registration_path(resource_name), class: "navbar-wagon-item navbar-wagon-link" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_pwa.html.erb
<link rel="manifest" href="/manifest.json">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="#FFF">
<meta name="apple-mobile-web-app-title" content="idk.">
<link rel="apple-touch-icon" href="<%= image_path 'idk-192.png' %>" />
<meta name="theme-color" content="#FFF"/>
<!-- iPhone SE (640px x 1136px) -->
<link rel="apple-touch-startup-image" media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)" href="<%= image_path 'idk-one.png' %>">
<!-- iPhone 8, 7, 6s, 6 (750px x 1334px) -->
<link rel="apple-touch-startup-image" media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)" href="<%= image_path 'idk-two.png' %>">
<!-- iPhone Xr (828px x 1792px) -->
<link rel="apple-touch-startup-image" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2)" href="<%= image_path 'idk-three.png' %>">
<!-- iPhone 8 Plus, 7 Plus, 6s Plus, 6 Plus (1242px x 2208px) -->
<link rel="apple-touch-startup-image" media="(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3)" href="<%= image_path 'idk-four.png' %>">
<!-- iPhone X, Xs (1125px x 2436px) -->
<link rel="apple-touch-startup-image" media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)" href="<%= image_path 'idk-five.png' %>">
<!-- iPhone Xs Max (1242px x 2688px) -->
<link rel="apple-touch-startup-image" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3)" href="<%= image_path 'idk-six.png' %>">
<!-- iPad Mini, Air (1536px x 2048px) -->
<link rel="apple-touch-startup-image" media="(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2)" href="<%= image_path 'idk-seven.png' %>">
<!-- iPad Pro 10.5" (1668px x 2224px) -->
<link rel="apple-touch-startup-image" media="(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2)" href="<%= image_path 'idk-eight.png' %>">
<!-- iPad Pro 11” (1668px x 2388px) -->
<link rel="apple-touch-startup-image" media="(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2)" href="<%= image_path 'idk-nine.png' %>">
<!-- iPad Pro 12.9" (2048px x 2732px) -->
<link rel="apple-touch-startup-image" media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2)" href="<%= image_path 'idk-ten.png' %>">