config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  devise_for :users, controllers: { registrations: :registrations, confirmations: 'confirmations' }
  root to: 'pages#home'
  get '/profile', to: 'pages#profile'
  get '/feed', to: 'pages#feed'
  get '/notifications', to: 'pages#notifications'
  resources :users, only: [:show] do
    resources :followers, only: [:create]
  end
  resources :followers, only: [:destroy]
  get '/followers/:user_id', to: 'followers#followers', as: 'followers'
  get '/following/:user_id', to: 'followers#following', as: 'following'
  get '/search', to: 'pages#search', as: 'search'
  resources :wishes, except: [:new, :create]
  resources :categories, only: [:index, :show]
  resources :events, except: [:new, :create] do
    resources :comments, only: [:index, :create]
    resources :likes, only: [:create]
    resources :hostings, only: [:create, :new]
  end
  resources :hostings, only: [:update, :destroy]
  resources :comments, only: [:destroy]
  resources :likes, only: [:destroy]
  resources :activities, only: [:show] do
    resources :events, only: [:new, :create]
    resources :wishes, only: [:new, :create]
  end
  resources :conversations do
    resources :messages
  end

  post '/', to: 'pages#wheel'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :activity
  has_many :hostings, dependent: :destroy
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :title, presence: true
  validates :description, presence: true
  validates :date, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_event, only: [:show, :update, :edit, :destroy]

  def index
    @events = current_user.events
    @hostings = Hosting.where(user: current_user.id, status: 'approved')
    @all_events = []
    @hostings.each do |hosting|
      @all_events << Event.find(hosting.event_id)
    end
    @all_events = @all_events + @events
    # @all_events = @all_events.reject { |event| event.date < Time.now }
    @all_events.sort_by { |event| event.date }
  end

  def new
    @event = Event.new
  end

  def show
    @activity = @event.activity
    @hosting = Hosting.new
    if params[:name]
      followers = current_user.followers
      following = Follower.where(follower_id: current_user.id)
      followers_array = []
      followers.each do |follower|
        followers_array << User.find(follower.follower_id)
      end
      following.each do |user|
        followers_array << User.find(user.user_id)
      end
      followers_array = followers_array.uniq
      search_results = User.search_by_firstname_and_lastname(params[:name])
      followers_array = followers_array.reject { |follower| Hosting.find_by(user: follower.id, event: @event) }
      @followers_array = followers_array & search_results
      @followers_array = @followers_array.sort_by { |user| user.first_name.downcase }
    else
      followers = current_user.followers
      following = Follower.where(follower_id: current_user.id)
      @followers_array = []
      followers.each do |follower|
        @followers_array << User.find(follower.follower_id)
      end
      following.each do |user|
        @followers_array << User.find(user.user_id)
      end
      @followers_array = @followers_array.uniq
      @followers_array = @followers_array.reject { |follower| Hosting.find_by(user: follower.id, event: @event) }.sort_by { |user| user.first_name.downcase }
    end
    guests = Hosting.where(event: @event, status: 'approved')
    @event_guests = []
    guests.each do |guest|
      @event_guests << User.find(guest.user.id)
    end
    pendings = Hosting.where(event: @event, status: 'pending')
    @pending_guests = []
    pendings.each do |pending|
      @pending_guests << User.find(pending.user.id)
    end
    @event_guests = @event_guests.sort_by { |user| user.first_name.downcase }
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @event = Event.new(event_params)
    @event.activity = Activity.find(params[:activity_id])
    @event.user = current_user
    if @event.title.empty?
      @event.title = @event.activity.title
    end
    if @event.description.empty?
      @event.description = @event.activity.description
    end
    if @event.date.nil?
      @event.date = Time.now
    end
    if @event.save!
      redirect_to event_path(@event)
    else
      render "events/new"
    end
  end

  def update
    @event.update(event_params)
    if event.save
      redirect_to event_path
    else
      render :edit
    end
  end

  def edit
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :date, :guests)
  end

  def find_event
    @event = Event.find(params[:id])
  end
end

app/views/events/_form.html.erb
<h1>Form</h1>

app/views/events/_user_info.html.erb
<div class="form-check">
  <input class="hidden" type="checkbox" value="<%= user.id %>" name="hosting[user_id][]" id="hosting_user_id_<%=user.id %>">
  <label class="user_choice" data-user-id="<%= user.id %>" for="hosting_user_id_<%= user.id %>">
    <div class="user-info" id="info-<%= user.id %>">
      <% if user.photo? %>
        <%= cl_image_tag(user.photo, width: 200, height: 200, crop: :fill, class:"avatar-large inactive", id: "user_avatar_#{user.id}") %>
      <% else %>
        <%= image_tag('default-avatar.png', width: 200, height: 200, crop: :fill, class:"avatar-large inactive", id: "user_avatar_#{user.id}") %>
      <% end %>
      <p id="name_<%= user.id %>" style="font-size: 11px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;"><%= "#{user.first_name.capitalize} #{user.last_name.capitalize}" %></p>
    </div>
  </label>
</div>

app/views/events/edit.html.erb
<%= render 'form' %>

app/views/events/index.html.erb
<div class="wrapper">
  <div class="container">
    <h2 class="page-title">your events<strong class="logo-period-profile">.</strong></h2>
    <% if @all_events.count.zero? %>
      <p>You haven't booked any events yet.</p>
    <% else %>
      <% @all_events.each do |event| %>
        <%= link_to event_path(event) do %>
          <div class="event-card">
            <div class="event-avatar">
              <%= cl_image_tag event.activity.photo, class: 'avatar-large' %>
            </div>
            <div class="event-info">
              <% unless current_user.id == event.user.id %>
                <p><%= "#{event.user.first_name.capitalize} #{event.user.last_name.capitalize} invited you to the event at" %></p>
              <% end %>
              <p><%= event.title %>, on <strong><%= event.date.strftime('%A, %b %d') %></strong></p>
            </div>
          </div>
          <hr>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<%= render 'form' %>

app/views/events/show.html.erb
<div class="wrapper">
  <div class="back-arrow">
      <%= link_to :back, class: 'back-to-conversations' do %>
        <%= image_tag 'left_arrow.png', class: "back-button" %>
      <% end %>
    </div>
  <div class="event-image">
    <%= cl_image_tag @activity.photo, class: 'event-photo' %>
  </div>
  <div class="container">
    <h5>You are going to <%= @event.title %>, on <strong><%= @event.date.strftime('%A, %b %d') %></strong><br><em>(<%= @event.guests %> going)</em></h5>
    <hr>
    <p><%= @event.description %></p>
    <hr>
    <div class="event-links" style="margin: 10px 0;">
      <div class="more-info">
        <%= link_to activity_path(@activity) do %>
          <p style="margin: 0"><i class="fas fa-info" style="margin: 0 5px 0 5px;"></i> More Info</p>
        <% end %>
      </div>
      <% if current_user.id == @event.user.id %>
        <div class="delete-event">
          <%= link_to event_path(@event), method: :delete do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        </div>
      <% end %>
    </div>
    <% if current_user.id == @event.user.id %>
      <div class="invite_users" data-toggle="modal" data-target="#inviteModel" type="button" >
        <button style="margin: 10px 0 0 0 !important; font-size: 15px; padding: 0; border: none; background: none;" ><i class="fas fa-users"></i> Invite friends</button>
      </div>
    <% else %>
      <%= link_to conversations_path(sender_id: current_user.id, recipient_id: @event.user.id), method: :post do %>
        <p style="margin: 10px 0 0 0;"><i class="fas fa-comments"></i> Contact host</p>
      <% end %>
    <% end %>
    <% unless @pending_guests.count.zero? %>
      <p style="font-size: 13px; opacity: 0.7;"><%= @pending_guests.count %> pending <%= 'guest'.pluralize(@pending_guests.count) %></p>
    <% end %>
    <div class="guests">
      <% @event_guests.each do |guest| %>
        <%= link_to user_path(guest), class:"guest" do %>
          <% if guest.photo? %>
            <%= cl_image_tag(guest.photo, width: 200, height: 200, crop: :fill, class:"avatar-large") %>
          <% else %>
            <%= image_tag('default-avatar.png', width: 200, height: 200, crop: :fill, class:"avatar-large") %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
  <div class="container">
    <div class="modal fade" id="inviteModel" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" style="margin-top: 60px;">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <h2 class="modal-title" id="exampleModalLongTitle">Invite your friends<strong class="logo-period-profile">.</strong></h2>
          </div>
          <div class="search">
            <%= form_tag(event_path(@event), method: :get, remote: true) do %>
              <%= text_field_tag(:name, "", placeholder: "find friends...", class:"searchTerm") %>
              <%= button_tag type: 'submit', name: nil, class: "searchButton" do %>
                <i class="fas fa-search"></i>
              <% end %>
            <% end %>
          </div>
          <%= simple_form_for [@event, @hosting] do |h| %>
            <fieldset class="form-group">
              <input type="hidden" name="hosting[user_id][]" value="">
              <div class="user_choices">
                <% @followers_array.each do |user| %>
                  <%= render 'user_info', user: user %>
                <% end %>
              </div>
            </fieldset>
            <div class="modal-footer">
              <%= h.submit "INVITE FRIENDS", class:"idk-button" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<%= content_for(:after_js) do %>
  <%= javascript_pack_tag 'components/user_choice' %>
<% end %>

app/views/events/show.js.erb
users = document.querySelector(".user_choices");
users.innerHTML = "";
<% @followers_array.each do |follower| %>
  followerAvatar = "<%= j render 'user_info', user: follower %>";
  users.insertAdjacentHTML('beforeend', followerAvatar);
<% end %>

// $(document).ready(function(){
//   $(".user-info").click(function(){
//     $(this).toggleClass("opaque");
//   });
// });

userChoices = document.querySelectorAll('.user_choice');
userChoices.forEach((choice) => {
  choice.addEventListener('click', () => {
    id = choice.dataset.userId;
    document.getElementById(`user_avatar_${id}`).classList.toggle('active');
  });
});