config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  devise_for :users, controllers: { registrations: :registrations, confirmations: 'confirmations' }
  root to: 'pages#home'
  get '/profile', to: 'pages#profile'
  get '/feed', to: 'pages#feed'
  get '/notifications', to: 'pages#notifications'
  resources :users, only: [:show] do
    resources :followers, only: [:create]
  end
  resources :followers, only: [:destroy]
  get '/followers/:user_id', to: 'followers#followers', as: 'followers'
  get '/following/:user_id', to: 'followers#following', as: 'following'
  get '/search', to: 'pages#search', as: 'search'
  resources :wishes, except: [:new, :create]
  resources :categories, only: [:index, :show]
  resources :events, except: [:new, :create] do
    resources :comments, only: [:index, :create]
    resources :likes, only: [:create]
    resources :hostings, only: [:create, :new]
  end
  resources :hostings, only: [:update, :destroy]
  resources :comments, only: [:destroy]
  resources :likes, only: [:destroy]
  resources :activities, only: [:show] do
    resources :events, only: [:new, :create]
    resources :wishes, only: [:new, :create]
  end
  resources :conversations do
    resources :messages
  end

  post '/', to: 'pages#wheel'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :activities, dependent: :destroy
end

app/controllers/categories_controller.rb
require 'open-uri'
class CategoriesController < ApplicationController
  skip_before_action :authenticate_user!

  def show
    @category = Category.find(params[:id])
    if @coordinates.all?
      @activities = Activity.by_distance(origin: @coordinates).where(category: @category)
    else
      @activities = Activity.where(category: @category)
    end
    if (@today.downcase.include? "rain") || (@today.downcase.include? "thunderstorm") || (@today.downcase.include? "snow") || (@today.downcase.include? "shower rain")
      @activities = @activities.reject { |activity| activity.tags.include?(Tag.find_by(name: "outdoors")) }
    end
    # @activities = Activity.joins(:tags).where(category: @category).where("tags.name ILIKE ?", params[:vibe])
    search_filter
  end

  private

  def search_filter
    if params[:number_of_people].present? || params[:who_are_you_with].present? || params[:location].present? || params[:vibe].present? || params[:and].present?
      search = params[:number_of_people].downcase + " " + params[:who_are_you_with].downcase + " " + params[:location].downcase + " " + params[:vibe].downcase + " " + params[:and].downcase
      @activities = Activity.search_by_activity_info(search).where(category: @category)
    end
  end
end

app/views/categories/show.html.erb
<input type="checkbox" id="toggle">
<aside class="sliding-panel">
  <div class="search-container text-center">
    <div class="row">
      <div class="col-xs-12">
        <%= form_tag(category_path(@category), :method => "get", id: "search-form", class: "form-group text-center") do %>
          <%= select_tag "number_of_people", options_for_select([ "Alone", "Couple", "Small Group", "Large Group" ], params[:number_of_people]), class: "form-control index-search", prompt: "Number of people" %>
          <%= select_tag "who_are_you_with", options_for_select([ "Parents", "Friends", "Mistress", "Partner", "Co Worker", "Someone from out of town", "Grandparents", "The Boys", "The Girls", "Boss" ], params[:who_are_you_with]), class: "form-control index-search", prompt: "Who are you with" %>
          <%= select_tag "location", options_for_select([ "Covent Garden", "Soho", "West End", "Southbank", "City of London", "Chinatown", "Camden Town", "Islington", "Hamstead", "Notting Hill", "South Kensington", "Shoreditch", "Peckham", "Brixton" ], params[:location]), class: "form-control index-search", prompt: "Location" %>
          <%= select_tag "vibe", options_for_select([ "Romantic", "Sexy", "Chill",  "Quiet", "Swanky", "Loud", "Trendy", "Posh", "Discreet",  "With a view" ], params[:vibe]), class: "form-control index-search", prompt: "Vibe" %>
          <% if @category.title == 'food' %>
            <%= select_tag "and", options_for_select([ "Dance", "Live music", "Celebrate",  "Best deals", "Talk business", "Im game for anything", "Treat myself", "Pop up", "Coffee", "Snacks", "Brunch", "Lunch", "Dinner", "Late night", "Sweets", "Vegetarian", "Vegan", "Pizza", "Sushi", "Steak", "Healthy", "Street Food"], params[:and]), class: "form-control index-search", prompt: "And.." %>
          <% elsif @category.title == 'drink' %>
            <%= select_tag "and", options_for_select([ "Dance", "Live music", "Celebrate",  "Best deals", "Talk business", "Im game for anything", "Treat myself", "Pop up", "Speakeasy", "Martinis", "Hotel bar", "Bougie cocktails", "Rave", "See a performance", "Pub"], params[:and]), class: "form-control index-search", prompt: "And.." %>
          <% elsif @category.title == 'adventure' %>
            <%= select_tag "and", options_for_select([ "Dance", "Live music", "Celebrate",  "Best deals", "Talk business", "Im game for anything", "Treat myself", "Pop up", "Get dirty", "Break a sweat", "Gallery", "Market", "Cultural trip", "Fast and furious", "Problem solve"], params[:and]), class: "form-control index-search", prompt: "And.." %>
          <% elsif @category.title == 'chill' %>
            <%= select_tag "and", options_for_select([ "Dance", "Live music", "Celebrate",  "Best deals", "Talk business", "Im game for anything", "Treat myself", "Pop up", "Detox", "Indoors", "Outdoors"], params[:and]), class: "form-control index-search", prompt: "And.." %>
          <% end %>
          <div class="search-update">
            <div class="position-center">
              <%= submit_tag "UPDATE", :name => nil, class: "search-button" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <label for="toggle">FILTERS</label>
  </div>
</aside>

<!-- CARDS -->

<div class="container no-gutters" style="margin-top: 25px;">
  <% if @category.title == "adventure" %>
    <h2 class="category-title text-center">play<strong class="play-show-dot">.</strong></h2>
  <% elsif @category.title == "chill" %>
    <h2 class="category-title text-center">chill<strong class="chill-show-dot">.</strong></h2>
  <% elsif @category.title == "drink" %>
    <h2 class="category-title text-center">drink<strong class="drink-show-dot">.</strong></h2>
  <% else @category.title == "food" %>
    <h2 class="category-title text-center">food<strong class="food-show-dot">.</strong></h2>
    <% end %>
  <br>
  <div class="row">
    <% @activities.each do |activity| %>
      <% if @coordinates.all? %>
        <% @distance = activity.distance_from(@coordinates, units: :kms) %>
        <% @direction = activity.heading_to(@coordinates) %>
      <% end %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <%= link_to activity_path(activity), id:"cardlink_#{activity.id}" do %>
          <div class="card" id="card_<%= activity.id %>">
            <div class="card-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= activity.photo %>');">
            </div>
            <div class="card-info" id="card_info_<%= activity.id %>">
              <% if activity.title.length >= 25 %>
                <p><%= "#{activity.title.upcase.first(25)}..." %></p>
              <% else %>
                <p><%= activity.title.upcase %></p>
              <% end %>
              <% if @distance && @direction %>
                <p style="font-size:12px; color: #C4C4C4;"><strong><i class="fas fa-map-pin" style="margin: 0 10px; font-size:16px;"></i></strong> <%= @distance.round(1) %>km</p>
              <% end %>
              <% if user_signed_in? %>
                <% unless Wish.where(user: current_user, activity: activity).count.zero? %>
                  <%= link_to wish_path(Wish.where(user: current_user, activity: activity).first.id), method: :delete, remote: true, id: "activity_#{activity.id}" do %>
                    <i class="fas fa-heart" style="color: #ED4956; font-size: 25px;"></i>
                  <% end %>
                <% else %>
                  <%= link_to activity_wishes_path(activity), method: :post, remote: true, id: "activity_#{activity.id}" do %>
                    <i class="far fa-heart" style="font-size: 25px;"></i>
                  <% end %>
                <% end %>
              <% else %>
                <%= link_to new_user_session_path do %>
                  <i class="far fa-heart" style="font-size: 25px;"></i>
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<!-- check that activity photo is replicated on all cards -->